image: rocker/r-base

stages:
  - dependencies
  - build
  - document
  - check
  - test
  - install 

default:
  tags:
    - docker

variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library
  CODECOV_TOKEN: "b524d434-9189-48fc-a919-72e40de8cd22"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
  - apt-get update

install_dependencies:
  stage: dependencies
  script:
    - Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
    - Rscript -e 'renv::restore()'
    - Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
    - Rscript -e 'devtools::install_deps(dependencies=c("Depends", "Imports", "Suggests"))'

buildbinary:
  stage: build
  script:
    - R -e 'devtools::build(binary=T)'

documentation:
  stage: document
  script:
    - R -e 'devtools::document()'

checkerrors:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  script:
    - R -e 'covr::codecov()'
    
install:
  stage: install
  script:
    - R -e 'devtools::install()'
