stages:
  - check
  - test
  - install

default:
  tags:
    - docker

variables:
  CODECOV_TOKEN: "b524d434-9189-48fc-a919-72e40de8cd22"
  NOT_CRAN: "true"

before_script:
  - micromamba activate base

check:
  stage: check
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker:cf0e84818d5d00d32d8dd4113d6af1628090f365
  script:
    - Rscript -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'
  only:
    refs:
      - master
      - dev
    changes:
      - R
      - tests
      - .gitlab-ci.yml

test: 
  stage: test
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker:cf0e84818d5d00d32d8dd4113d6af1628090f365
  script:
    - Rscript -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'
    - Rscript -e 'Sys.setenv(NOT_CRAN = "true");covr::codecov(token="b524d434-9189-48fc-a919-72e40de8cd22")'
    - bash <(curl -s https://codecov.io/bash)
  only:
    refs:
      - master
      - dev
    changes:
      - R
      - tests
      - .gitlab-ci.yml


install:
  stage: check
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker:cf0e84818d5d00d32d8dd4113d6af1628090f365
  script:
    - Rscript -e 'devtools::build(binary=T)'
    - Rscript -e 'devtools::install()'
  only:
    refs:
      - master
      - dev
    changes:
      - R
      - .gitlab-ci.yml
