stages:
  - check
  - test
  - install

default:
  tags:
    - docker

variables:
  RENV_PATHS_ROOT: "/opt/r_renv"
  CODECOV_TOKEN: "b524d434-9189-48fc-a919-72e40de8cd22"

before_script:
  - Rscript -e 'renv::restore()'

check:
  stage: check
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker
  script:
    - Rscript -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'

test: 
  stage: test
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker
  script:
    - Rscript -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'
    - Rscript -e 'covr::codecov()'

install:
  stage: check
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/tableextra_docker
  script:
    - Rscript -e 'devtools::build(binary=T)'
    - Rscript -e 'devtools::install()'
