stages:
  - dependencies
  - build
  - document
  - check
  - test
  - install 

default:
  tags:
    - docker

variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library
  CODECOV_TOKEN: "b524d434-9189-48fc-a919-72e40de8cd22"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
  - Rscript -e "renv::paths$root()"
  - echo ${CI_PROJECT_DIR}
  - apt-get update
  - apt-get install --yes libcurl4-openssl-dev # required for installing R package "curl"
  - apt-get install --yes libgit2-dev # required for R package "git2r"
  - apt-get install --yes libssl-dev # required for R packages "git2r" and "openssl"
  - apt-get install --yes libssh2-1-dev # required for R package "git2r"
  - apt-get install --yes libxml2-dev # required for R package "xml2"
    
install_dependencies:
  stage: dependencies
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
    - Rscript -e 'renv::restore()'
    - Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'

buildbinary:
  stage: build
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'devtools::build(binary=T)'

documentation:
  stage: document
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'devtools::document()'

checkerrors:
  stage: check
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'

unittests:
  stage: test
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'covr::codecov()'
    
install:
  stage: install
  image: gitlab-research.centralesupelec.fr:4567/2019pradaty/rcached
  script:
    - R -e 'devtools::install()'
