image: continuumio/miniconda3:latest

stages:
  - check
  - test
  - install

default:
  tags:
    - docker

variables:
  CODECOV_TOKEN: "b524d434-9189-48fc-a919-72e40de8cd22"

before_script:
  - conda env create -f env.yaml
  - source activate tableExtra

check:
  stage: check
  script:
    - Rscript -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'
  only:
    refs:
      - master
      - dev

test: 
  stage: test
  script:
    - Rscript -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'
    - Rscript -e 'covr::codecov(token="b524d434-9189-48fc-a919-72e40de8cd22")'
    - bash <(curl -s https://codecov.io/bash)
  only:
    refs:
      - master

install:
  stage: check
  script:
    - Rscript -e 'devtools::build(binary=T)'
    - Rscript -e 'devtools::install()'
  only:
    refs:
      - master
